### ISSUE TITLE
int-to-string in function “Open with VSCode”

### ISSUE THREAD

**Issue by suliveevil** [pietroiusti/.emacs.d#1]
```emacs-lisp
(defun my/open-in-vscode ()
  (interactive)
  (start-process-shell-command "code"
                               nil
                               (concat "code --goto "
                                       (buffer-file-name)
                                       ":"
                                       (int-to-string (line-number-at-pos))
                                       ":"
                                       (int-to-string (current-column)))))
```

In this way, we don't need `1+` workaround.

**Comment by suliveevil** [comment]
Somehow, my column number in Emacs and VSCode didn't keep parallel (one char ahead in VSCode).

**Comment by pietroiusti** [comment]
Hey, thanks! Yesterday I was trying that function on my personal machine (I usually use vscode on my work laptop) and I ended up with the same you are suggesting. For some reason current-line was undefined... I have to the column mismatch as well. BTW, do you happen to know how to do the same in vscode?

**Comment by suliveevil** [comment]
>  how to do the same in vscode?

VSCode's builtin variables only have line numbers no column numbers.

Use this Plugin and put this in your settings.json:

https://github.com/tjx666/open-in-external-app

```
    "openInExternalApp.openMapper": [
        {
            "extensionName": "*",
            "apps": [
                {
                    "title" : "Open in Emacs",
                    "isElectronApp": false,
                    "shellCommand": "emacs +${cursorLineNumber}:${cursorColumnNumber} ${file}"
            }
        ]
        }
    ],
```

**Comment by pietroiusti** [comment]
fantastic, thank you, I'll try
